---
functional:
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность выбирать уровень игры
  - Пользователь должен иметь возможность выбирать тип игры
  - Пользователь должен иметь возможность выбирать ограничение по времени
  - Пользователь должен иметь возможность выбирать задание по названию или тегу
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - У сайта должен быть приятный дизайн
  - Регистрация и аутентификация пользователей
  - Оптимизация для поисковых систем
  - Локализация
